apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vision-model-pvc
  namespace: disaster-monitor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
