apiVersion: v1
kind: ServiceAccount
metadata:
  name: vision-service-sa
  namespace: disaster-monitor
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::264935030068:role/my-mlops-prod-vision-service-pod-role
